language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test 
deploy:
  provider: heroku
  api_key: e45ed230-a1c7-43ab-9430-bf38d67b8f10
  app: myrsoi
